### ISSUE TITLE
Gjøre nettsiden mobilvennelig

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#11]
Akkurat nå er ikke siden spesielt mobilvennlig. Så dette er noe vi må se på innen vi er ferdig med prosjektet

**Comment by proghodet** [comment]
Godt poeng! Jeg kan godt sette opp viewports og slikt, men selve designet er vel kanskje greit å drøye litt uansett. En annen ting, er det egentlig relevant for denne oppgaven at siden er mobilvennlig? Kan sikkert fyre av en mail til Bjørn og høre om det er verdt å bruke tid på det :) ### Unnskyld at jeg spør! :O

**Comment by proghodet** [comment]
Jeg hadde tenkt til å begynne å se på dette i dag, men så slår det meg at det er nok ikke hverken lurt eller nødvendig å styre med det, inntil vi har et design som vi er tilfreds med? Blir bare dobbelt arbeid dersom vi må endre både vanlig css og mobilcss fremover.. :)

**Comment by ruffe1989** [comment]
Her har du påpekt at ved bruk av bootstrap blir dette gjort veldig enkelt. Så tror ved å gå over til bootstrap løser vi denne issuen

**Comment by ruffe1989** [comment]
Som Bjørn nevnte i dag er det ikke veldig viktig at den er mobilvennelig. så jeg lukker denne issuen
