### ISSUE TITLE
Forbedre admin siden

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#12]
Admin siden trenger egentlig ikke å ha samme layout som resten av siden. Så vi kan kanskje gjøre den litt mer "fancy". 
Jeg tenkte også at vi kanskje skulle gjort slik at admin siden har litt flere funksjoner enn kun det å opprette et nytt arrangement. 
Det jeg tenkte vi kunne fått ordnet er å gi admin mulighet til å kunne se hvor mange solgte billetter. 
Kom gjerne med flere forslag til funksjoner admin siden kan ha

**Comment by proghodet** [comment]
Fancy som i flere funksjoner, eller tøffere css? :D

Det å la admin få et bittelite statistisk innblikk er en kjempegod idé! Kanskje få se hvor mange som har vært inne på sida, hvor mange som har vært innom vært individuelle arrangement. Som du nevner, se antall solgte billetter, både totalt, og pr arr.

**Comment by martinemdal** [comment]
Hadde vært veldig fint om adminsiden har en liten liste av arrangementbullets (gjerne med bilder og sånt) hvor admin kan slette gamle arrangement.

**Comment by ruffe1989** [comment]
Jeg ser for meg litt at vi her bruker litt annet design enn hva som blir brukt på resten av siden. Det er det som er normalt for admin sider. et eksempel er: 
![image](https://cloud.githubusercontent.com/assets/20629799/23699367/311722c8-03ef-11e7-8086-7d3538533269.png)

**Comment by ruffe1989** [comment]
Vi skulle hatt mulighet til å kunne endre header bilde på admin siden også

**Comment by proghodet** [comment]
Slett arr.
Lag arr.
Endre headerbilde
Dashboard ( se antall billetter )
Users

**Comment by proghodet** [comment]
Jeg har laget admin.php, og der ligger det (foreløbig) bare en nav, som linker til de forskjellige funksjonene.

Jeg har laget userList.php som lister ut alle brukere i databasen i en tabell - ikke noe fancy der.

Jeg har laget deleteArr.php, der du får en liste over alle arrangement, velger en radioknapp, og trykker utfør for å slette. Vi bør ha en js popup som spør om du er sikker på at du vil avlyse arrangementet - et ekstra ledd er bra for at man ikke sletter i tide og utide.

Et par ting å tenke på angående denne siden: skal vi sende raden som slettes til en CSV-fil? skal den legges i en annen tabell? Kanskje vi skal slenge inn en column som heter Avlyst, og at denne blir satt til true ved sletting - og at alle funksjoner som viser arrangement kun skal vise Avlyst = False?

Kom med argumenter for og imot forskjellige løsninger, men dataene bør iallefall ikke forkastes etthundre prosent.

**Comment by proghodet** [comment]
Dersom noen har ønsker om mer funksjonalitet, eller finner bugs and stuffs, så lag en ny issue, og merk med henholdsvis Enhancement eller Bugs, og assign det til meg, så skal jeg se på det :)

Men ellers tenker jeg at denne tråden kan lukkes.
