### ISSUE TITLE
Design-overhaling

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#13]
Vet ikke om jeg er alene på det, men syns utseende på nettsiden nå er litt kjedelig. Derfor må vi gå igjennom og forbedre utseende på siden

**Comment by proghodet** [comment]
Jeg gir blanke i design, og jeg vet ikke om Bjørn vurderer utifra design når han setter karakter. Men det er kanskje verdt å spørre han om? Igrunn samme med mobilvennlighet. Bare så vi ikke skyter oss i foten og bruker masse tid og tankearbeid på stuff som ikke gir uttelling uansett :) Jeg kan godt fyre av en mail til han dersom andre også vil :)

**Comment by ruffe1989** [comment]
Vi har fått bekreftet at vi kan bruke bootstrap, så jeg kommer til å bruke dette til design forbedring

**Comment by MagnusMango** [comment]
Vise at personen er logget inn
(bytte ut logg inn med brukernavn og eventuelt logg ut knapp ved sidna?)

**Comment by ruffe1989** [comment]
Jeg velger å lukke denne nå, da jeg mener den mer eller mindre er ferdig. Lager eventuelt nye små issues til det som eventuelt gjenstår.
