### ISSUE TITLE
Trigger

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#14]
Punkt 9 krever at vi har en trigger i databasen.
Diskuter gjerne under hvor det kunne vært hensiktsmessig

Trigger: Når noe forsøkes i databasen, så "trigges" en eller annen utførelse.

**Comment by martinemdal** [comment]
La til en trigger for sletting av billetter ved sletting av arrangement.

**Comment by proghodet** [comment]
Bonus: Flere triggere!

**Comment by ruffe1989** [comment]
Ikke behov for flere triggere
