### ISSUE TITLE
Lagret rutine

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#15]
Vi må ha en lagret rutine i databasen.
En lagret rutine er som en metode som vi kjenner fra Java.

Vi kan enten lage en funksjon (har en returverdi), eller en prosedyre (void-metode).
Kom gjerne med forslag til hvilke lagrede rutiner som hadde vært hensiktsmessige i vårt prosjekt!

**Comment by martinemdal** [comment]
Gjerne ha alle manipuleringer av databasen som rutiner og ikke direkte i phpskript. Gir en viss form for innkapsling, og også en ryddigere design.

**Comment by martinemdal** [comment]
typ noe som:
SELECT name, EventID
FROM arrangement
WHERE aktiv = 1

eller noe.

**Comment by MagnusMango** [comment]
Done :)
