### ISSUE TITLE
Forretningsregler

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#16]
Noe vi ønsker å hindre (kaste unntak, gi mysqli_errno i PHP). Vi må ha minst to av dem.

Oppgave 5 leksjon 8 er meget relevant!

Diskutér under hvilke forretningsregler som kan være relevant for oppgaven.

**Comment by ruffe1989** [comment]
Vi kunne hatt en forretningsregel som rammer det å lage ny bruker. Her kan man velge mellom det at man ikke kan ha passord som ikke inneholder noen spesifiserte bokstaver eller lignende. f eks er det jo ofte at man ikke får lage passord som ikke inneholder både stor og liten bokstav. Men samme kan gjelde hvordan eposter blir skrevet.

**Comment by ruffe1989** [comment]
Kanskje en forretningsregel for hvor mange billetter man har lov å kjøpe i ett kjøp?

**Comment by martinemdal** [comment]
Kanskje forhindre registrering av brukere med duplikate epostadresser?

**Comment by MagnusMango** [comment]
Min-max lengde på brukernavn?

**Comment by proghodet** [comment]
Vi setter opp to:
Maks 10 billetter pr. arrangement
Min / maks lengde på brukernavn

BONUS, hvis tid - sleng på flere!

**Comment by ruffe1989** [comment]
Siden det ikke vil være hensiktsmessig å lage en forretningsregel for brukernavn, da dette blir dekket i php fila lager jeg heller disse forretningsreglene
- admin ikke kan lage arrangement lengre enn 1 år frem over i tid
- admin kan ikke oppdatere prisen mer enn så og så mange kr
