### ISSUE TITLE
Sikre mot SQL-injections

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#18]
Gå igjennom alle filer, og (dobbelt)sjekke at alt av tekstfelt som sender info til databasen er sikret mot SQL-injections.

**Comment by proghodet** [comment]
Dette bør forøvrig lages som en metode, og deretter bare kalles på der den trengs

**Comment by proghodet** [comment]
Fint eksempel i createUser.php

**Comment by ruffe1989** [comment]
Hvordan ligger du ann her Magnus?

**Comment by MagnusMango** [comment]
Laget en metode/function som tar for seg alle trim, specialhtmlchars ogsånn så må bare gå igjennom og finne alle variabler så er jeg ferdig.

**Comment by MagnusMango** [comment]
Da er det ferdig om noen ser noe jeg har missed si gjerne ifra! skal ta en titt til før vi leverer.
