### ISSUE TITLE
Legge til ekstra "ledd" i sletting av arrangement

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#19]
Kom gjerne med andre forslag, men vi bør hvertfall ha en javascript alert-box for å sjekke om admin er sikker på at han vil slette arrangement. Slik den er nå velger du radioknapp, trykker utfør, og så blir det slettet - FOR EVIG.

**Comment by MagnusMango** [comment]
Siden denne er merged kan vi lukke den?

**Comment by martinemdal** [comment]
Funker nå, men sliter med å få knappene til å sitte pent
