### ISSUE TITLE
Facebooklogin

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#2]
Single sign on. Dersom man har en facebook-account skal man kunne logge inn og bestille seter.

Vi må derfor ha mulighet til å kunne hente ut info fra facebook - hvertfall epostadresse (for å få tilsendt billett)

**Comment by proghodet** [comment]
https://developers.facebook.com/docs/facebook-login/web

**Comment by ruffe1989** [comment]
Er litt usikker på om vi faktisk skal bruke dette.

**Comment by proghodet** [comment]
Vi er enige om å ikke bruke tid på dette. Føkk facebook.
