### ISSUE TITLE
editHeader.php

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#20]
Skal gi mulighet for admin til å laste opp et nytt bilde, og bruke som headerbilde.

**Comment by proghodet** [comment]
Hiver umiddelbart på et spørsmål til denne:

Ettersom vi bruker en karusell av bilder (slideshow), skal vi egentlig bare gjøre slik at bildet som blir lastet opp legges til i karusellen? Eller skal den fjerne alle bildene som ligger der?

**Comment by martinemdal** [comment]
Jeg synes den kan gjerne bare legges til karusellen til å begynne med, så får vi se om vi kan lage en mer avansert løsning etterhvert?

**Comment by MagnusMango** [comment]
Enig med Martin kanskje ha en maks grense på hvor mange som kan ligge der eller at de fjernes når arrangemanget er ferdig.

**Comment by ruffe1989** [comment]
Tanken jeg hadde med karusellen var at når admin endrer med editHeader bytter ut eller sletter han bildene som er der. Ikke at det legges enda flere til. Jeg vet ikke helt om vi skal ha slidshowet til å vise arrangement eller. For de bildene ligger jo lengre ned på siden.

**Comment by ruffe1989** [comment]
Fikse størrelse på header slik at den tilpasser seg hvilken skjerm den er koblet til

**Comment by proghodet** [comment]
Vi fjerner "last opp bilde" på admin, og legger til at karusellen viser bilde basert på antall solgte billetter i databasen

**Comment by ruffe1989** [comment]
Nå er dette ordnet
