### ISSUE TITLE
Hva er sletting av arrangement?

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#21]
Vi bør finne en måte å definere "slett arrangement".

Som jeg har nevnt tidligere, så mener jeg at dataene godt kan flyttes, eller endres, men at de aldri bør slettes, pga historikk. Mitt forslag er å legge til en kolonne i databasen som heter Aktiv / Avlyst / On / et eller annet som vi kan legge inn True / False på.

Dersom arrangementet er bekreftet og alt er fint, så vises den i alt av tabeller, og hvis ikke, så vises arrangementet _ikke_ . 

Your thoughts? :)

**Comment by martinemdal** [comment]
Den virker veldig fin i førsteomgang. Synes vi burde gjøre det slik. Eventuelt restrukturere databasen "down the road" hvis det skulle vise seg være problematisk.

**Comment by proghodet** [comment]
Dersom jeg ikke får noen innvendinger på den løsningen i løpet av kvelden legger jeg til kolonna i sql-skriptet og pusher det enten i dag eller i morgen :)

**Comment by MagnusMango** [comment]
Husker ikke om det var Rolf eller Martin som sa det men vi kunne jo lage en "ferdige" som arrangemanget blir flyttet over til når den er ferdig.

**Comment by proghodet** [comment]
Jeg tenker at det har liten eller ingen hensikt å bare flytte dataen til en annen tabell - den totale mengden av data i  databasen blir likevel den samme, så da ble det bare den ekstra kolonna som jeg nevnte for noen dager siden. 

Da lukker jeg denne :)
