### ISSUE TITLE
Datoform i program.php

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#22]
MySQL leverer dato på følgende form:
2017-05-05 20:00:00

men vi ønsker vel heller å ha klokkeslett i egen kolonne, med tt:mm, og datoen i egen kolonne med formen dd-mm-åååå / dd-mm-åå ?

**Comment by proghodet** [comment]
Legge til kolonne i databasen med TIME og endre kolonnen Dato til KUN dato (ikke klokkeslett)

**Comment by MagnusMango** [comment]
Done!
