### ISSUE TITLE
Korrekturlesning

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#34]
Se over alt av brukerdialog og lesbar tekst for brukere på sida. Kode gjennomgåes ikke naturligvis.

Drøyer dette til absolutt alle funksjoner er på plass ( altså i månedsskiftet ), så ikke det sniker seg inn feil på slutten.

**Comment by martinemdal** [comment]
Replace in files og søke opp ord som ofte skrives feil kan ta endel sånn at det blir lettere å kamme etterpå.
