### ISSUE TITLE
Petition om å forandre database

### ISSUE THREAD

**Issue by martinemdal** [proghodet/utested#36]
Hadde vært fint hvis vi kunne forandre primary key for ticket til å være eventID + seatID. Gjør bestilling av billetter litt mer smooth. Forandrer det gjerne selv hvis alle syns det er ok.

Gjør det mulig med:
insert into ticket (eventid, seatid, personid)
values (1, 2, 3)

noe som ikke er mulig hvis "duplikate" seter er mulig pga ticketID er primarykey. (eg. blir en ekstra spørring opp mot db).

**Comment by ruffe1989** [comment]
Hvis det bidrar til å forenkle prosessen, så sier jeg; go for it.

**Comment by proghodet** [comment]
Fikk ikke med meg denne, men ja, selvsagt bare bytt hvis det er
hensiktsmessig :)

24. mars 2017 kl. 10:44 skrev ruffe1989 <notifications@github.com>:
