### ISSUE TITLE
Endre datoformat på program siden

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#38]
Tittel forklarer nok. Datoformen er ikke helt riktig i tabellen. Men ellers ser tabellen mye finere ut nå og med bestilling knapp.

**Comment by MagnusMango** [comment]
<img width="1204" alt="screenshot 2017-03-26 03 30 29" src="https://cloud.githubusercontent.com/assets/23613878/24327561/99e8f298-11d4-11e7-8c30-87b169cbaa1e.png">

**Comment by MagnusMango** [comment]
hva er problemet?

**Comment by MagnusMango** [comment]
<img width="543" alt="screenshot 2017-03-27 23 26 46" src="https://cloud.githubusercontent.com/assets/23613878/24378884/de072000-1344-11e7-8617-a32892c62d05.png">
Y boooooy
