### ISSUE TITLE
Hvilke emner vil vi ha i <nav>?

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#4]
Vi trenger å bestemme oss for hvilket innhold vi ønsker i navigasjonen i toppen av siden.
Vi har nå program, kontakt, om oss, annet og admin. 

Derfor lurer jeg på, hvilke undersider MÅ vi ha med?

Deretter må naturligvis linkene i nav'en peke på riktige php-sider

**Comment by ruffe1989** [comment]
Jeg tenker at den program nav, skal gå til en lengre liste av ting som skjer. Eller hva tenker dere? Admin ser jeg for meg at vi skal fjerne fra naven og heller plassere en annen plass. For er ikke vits at admin innlogging har egen fane eller?

**Comment by proghodet** [comment]
Jeg skreiv feil! admin er allerede fjernet - den heter nå logg inn, og fungerer for både admins og kunder :)

![screenshot_1](https://cloud.githubusercontent.com/assets/20617365/23022380/bf4cc60a-f450-11e6-9d53-9e69f4cb2312.png)

Jeg tenkte at "program" gikk til hovedsiden, men det er kanskje ikke så dumt å ha en full liste over arrangementene i tillegg?

**Comment by proghodet** [comment]
JavaScript: Lys opp aktiv fane.

Hjem: index.php
Program: Skal gi en tabell med kun arrangementnavn og dato
Kontakt: Kontaktinfo, kart og historie om stedet
Bestilling: seatbooking.php (eller login.php hvis ikke er logget inn)
Logg inn: login.php

**Comment by proghodet** [comment]
Har nå laget Programside ( tabell som henter alle navn på arrangement fra databasen med dato)
Har også laget kontaktinfo, med JavaScript google-maps og standard kontaktinfo.

Rolf tar seg av endring av nav-elementer.
