### ISSUE TITLE
CSS på endring av arr

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#46]
F.eks:
http://localhost/utested/update.php?EventID=2

Smertefullt midstilt, hehe.

**Comment by MagnusMango** [comment]
Done, greit med feedback fra de med store skjermer :P

**Comment by ruffe1989** [comment]
Ser veldig bra ut. Har lagt inn slik at den ikke går vekk fra update med en gang. For det gjorde at man ikke fikk sett feilmeldinger som kunne komme fra databasen. Så la til en knapp som avslutter redigering i stedet. Men ellers ser det veldig bra. Så jeg avslutter denne issuen
