### ISSUE TITLE
Gjør karusellbilder til linker til arrangementsiden?

### ISSUE THREAD

**Issue by martinemdal** [proghodet/utested#54]
Å klikke på karusellbildet gjør ingenting akkurat nå.

**Comment by proghodet** [comment]
Denne er kjip! Dersom man slenger inn en <a href> inni karuselloppsettet så føkker det med bildejustering og størrelser. den generelle a-taggen arver nok mye css fra rundtomkring, i tillegg til at karusellen åpner mange tags, og stenger alle helt på slutten. GL HF, hvem enn som hopper på denne.. hehe

**Comment by ruffe1989** [comment]
Siden de bildene under er klikkbare syns jeg ay vi dropper denne.
