### ISSUE TITLE
Login tar med seg info

### ISSUE THREAD

**Issue by ruffe1989** [proghodet/utested#55]
Her tenkte jeg litt på det at hvis man f eks trykker på kjøp billett til et arrangement i program så blir man sendt til login og deretter skal den gå videre til det valgte arrangementets bestilling og ikke måtte gå tilbake til program og trykke på knappen på nytt

**Comment by proghodet** [comment]
Jaaaa! Tommelopp! Har tenkt på det samme hver gang jeg har testet siden selv. Irritasjonsmoment! :P

**Comment by ruffe1989** [comment]
Har prøvd å finne ut en god måte å gjøre dette på, men er usikker på hvordan jeg skal gå frem. Det ser ut til en session variabel vil være lurt å gå for. Men er usikker på hvordan det skal ordnes siden program siden er laget med en foreach.

**Comment by ruffe1989** [comment]
Skal denne droppes eller hva gjør vi her?

**Comment by martinemdal** [comment]
La inn ta med info ved innlogging nå.
