### ISSUE TITLE
Unngå strekking av bilder i slideshow

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#56]
Title says it all!

**Comment by ruffe1989** [comment]
Jeg har prøvd meg litt frem her. Men har ikke funnet et br alternativ. Så hvis andre kan prøve å se om de finner noen måte å løse det på hadde det vært flott

**Comment by proghodet** [comment]
Jeg sitter og holder på med det nå - kommer med oppdatering om jeg finner noe spennende :)

**Comment by proghodet** [comment]
done deal
