### ISSUE TITLE
Haster! Endring av createArr

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#63]
Vi ønsker å ha en ekstra tekst-boks i create arr, som heter longDescription, der admin kan skrive inn lang informasjon om arrangementet. Denne informasjonen legges på fil og knyttes til arrangementet (og vises på hver arrangementsside). 

Tekstboksen som ligger der fra før av kan bare fortsette å hete description, og er den teksten som skal sendes til databasen. Denne teksten skal (og vises allerede) på forsiden, under hvert arrangement.

**Comment by martinemdal** [comment]
Kan gjøre det nå. Bjørn ville forresten at vi hestlagret tekst i databasen framfor på fil. Tenker jeg gjør det hvis du ikke har noen innvendinger. Skal forandre de andre skjemadataene til å gå til bare databasen også.

**Comment by ruffe1989** [comment]
Grunnen til at det ikke skulle legges inn i databsen var fordi joachim har nå tatt bilde av databasen så hvis du skal lage en ekstra del i databasen må dette gjøres på nytt siden det da er et nytt element som blir lagt til i databasen. Joachim snakket om at vi eventuelt kan ha en funksjon på forsiden som heller klipper ut den første setningen av beskrivelsen. Så at vi kan da eventuelt skrive i placeholderen der at den første setningen blir den som kommer frem på forsiden. Og at den er viktig å forklare kort arrangementet

**Comment by martinemdal** [comment]
Skal legge inn på fil for nå, men anbefaler at vi bytter til database før innlevering for best mulig karakter.

**Comment by proghodet** [comment]
Jeg vet denne er stengt, men ville bare slenge inn; det er selvsagt ikke noe problem å legge det i databasen, men bare kjipt å gjøre samme ting flere ganger, hehe. Tar ikke sååå lang tid å ta et nytt bilde av db'en :) Viktigere at vi gjør det riktig :)

**Comment by martinemdal** [comment]
Kan være en forandring vi tar down the road uansett :) Viktigst at vi jobber framover og ikke bakover. Så enig i at er kjipt å gjøre ting flere ganger. Blir vel en oppussing på oppussingen om et par uker og! :D

**Comment by proghodet** [comment]
.. Skal ikke se bort i fra det, hehe :)
