### ISSUE TITLE
Milepæl 3

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#64]
Innen onsdag 19. April:

Hele innleveringen skal pakkes i én zip-fil og lastes opp i Fronter. Zip-filen skal inneholde:

- Selve applikasjonen (på en egen mappe), som etter utpakking, skal kunne kjøres lokalt på XAMPP. Sjekk spesielt at dette fungerer også med eventuelle ekstra programbiblioteker som blir brukt.
- SQL-skript som oppretter databasen, tabeller, triggere, lagrede prosedyrer, og som dessuten setter inn testdata.

- Oppdatert beskrivelse av applikasjonen.

- Kort forklaring av installasjon og oppretting av database med testdata, inkludert brukernavn og passord til testbrukere.

- Opplisting av hvilke bøker og nettressurser man har brukt.

Gruppene skal legge opp til å bruke samme mappenavn og databasenavn som man får utdelt på itfag.usn.no, slik at det blir enkelt å kjøre flere applikasjoner samtidig på XAMPP.

**Comment by ruffe1989** [comment]
Jeg så også igjennom kravene. Det er fortsatt noen småting som ikke er på plass der. Disse er:
- siden skal ha en mulighet til kontroll av validering av siden
- siden skal bruke sesjoner og ikke cookies som vi har valgt.
Ellers er alle kravene i boks.

**Comment by ruffe1989** [comment]
Beskrivelse ferdig skrevet. Tar resten senere i dag

**Comment by proghodet** [comment]
På stell, planer i boks. 

Kodeskriving skal være ferdig innen 15:00, Onsdag 19. April
Deretter skal siden testes grundig, frem til 18:00 samme dag, og da leverer vi oppgaven.
