### ISSUE TITLE
createArr (omfattende)

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#7]
Use Case: Lag arrangement (for admin)

1) admin logger inn
2) admin legger inn alle hensiktsmessige infofelt om arrangement
3) admin trykker lagre
4) Tekstlig info blir lagret i databasen og bilder blir lagret i /img/arr/[navn på arr]/[løpenummer].jpg
5) Denne lenken sendes også til databasen, slik at arr er linket mot bilder
6) Det opprettes en egen php-fil som følger en mal, med all info om arrangementet.
	a) filen innehar html og php for å opprette siden, og henter deretter info fra opprettet 	arrangement

**Comment by ruffe1989** [comment]
Jeg tenkte litt på at admin siden trenger nødvendigvis ikke å ha samme layout og slikt som resten av siden. Men det er noe vi kan vurdere. Man ser jo på andre cms at den har egen layout på admin siden enn hvordan hovedsiden ser ut.

**Comment by proghodet** [comment]
Det er bare css-stæsj - tar lang tid å diskutere, kort tid å utføre. 
Jeg tenker mao. at vi ikke stresser med det enda, men hvis flere er enige om at adminsiden bør ha en annen look, så skal vi alltids få fiksa det :)

**Comment by martinemdal** [comment]
Trenger å lage en parser som kan lese og forandre innhold på hovedsiden. Eller å lagre all visningsinfo i en database. Kommer til å ta litt tid men vi har hatt det i algdat (jippi).

**Comment by martinemdal** [comment]
Ok så vi ble enige om å lagre visninginformasjon på disk, med en passende navnekonvensjon.

**Comment by martinemdal** [comment]
Ok godt på vei nå, men trenger å vite endel mer om hvordan layouten skal være før man kan gjøre så mye mer atm. Føler vi burde lage noen mockups som viser hvordan vi vil visningsidene skal se ut til slutt. Regner med hovedsiden sin struktur er satt? Hvis ikke burde forandringer på index.php også gjøres i createArr slik at ikke den forandrer utseendet på den.

**Comment by proghodet** [comment]
Jeg var frekk og endret litt på denne - hovedsaklig gikk jeg vekk fra input type="datetime-local", ettersom denne kun er støttet av et knippe browsere. Har splittet dem til henholdsvis date og time. 

Har også prøvd å konkretisere hvert felt litt bedre, og endret placeholders.

![screenshot_2](https://cloud.githubusercontent.com/assets/20617365/24045807/a0557fb2-0b20-11e7-9b18-a91dafb8b58d.png)

**Comment by ruffe1989** [comment]
Da blir denne lukket og små issues blir laget i stedet
