### ISSUE TITLE
Booking av sete

### ISSUE THREAD

**Issue by proghodet** [proghodet/utested#9]
GUI, javascript.

1. Kunde logger inn
2. Kunde velger aktuelle arrangement fra... en drop-down meny? En meny iallefall.
3. Kunde får grafisk vist ledige og opptatte plasser (med logisk fargekoding - grønn og rød?)
4. Kunde velger antall billetter
5. Kunde trykker på en plass, og får antall plasser så nært som mulig der de trykket.
6. Kunde trykker "Bestill"
7. eMail blir sendt til kunde, med info om seteplass, og arrangement

Husk: Punkt 6 i oppgavebeskrivelsen må oppfylles!
(Sammensatt transaksjon + presentere flere rader fra tabeller)

**Comment by ruffe1989** [comment]
Ved at du klikker inn på et spesifikt arrangement så legger den inn info om hvilket arrangament det er slik at den da henter ut informasjon fra rett rad i tabellen.

**Comment by proghodet** [comment]
Hvordan ligger denne an, monsieur Emdal? :)
